### ISSUE TITLE
Please add Marianne2020.com to presidential candidates 

### ISSUE THREAD

**Issue by LarryHallas** [benjaminp/httpswatch#108]
Please add the campaign website for Marianne Williamson for President, Marianne2020.com to HTTPSWatch listing of presidential campaigns.

Thank you,
Larry Hallas
Cybersecurity for Marianne Williamson for President
larry@marianne2020.com

**Comment by alex** [comment]
I do not believe there is any objective standard by which she is sufficiently notable. She has never held elected office, I'm not aware of a poll including her, and I don't believe she qualifies by any of the DNC's debate inclusion criteria.

**Comment by LarryHallas** [comment]
Hi Alex,

Marianne Williamson is a viable candidate with the largest social media
following of almost any candidate. She has over 2.6 million twitter
followers and 760k Facebook followers. She is listed almost every major
news outlets as one of the 16 candidates currently declared (google
Presidential Candidates 2020). Marianne is on track to be included in the
Democratic debates in June, and has raised well over $1 million in
donations. I would ask that you please reconsider.

Thank you very much for your time,

Larry Hallas, BS/MIS, VCP, MCT, MCSE, MCDBA
Cybersecurity at Marianne Williamson for President
larry@marianne2020.com
954-556-0011
http://www.marianne2020.com

**Comment by benjaminp** [comment]
I agree with Alex.
